[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@solmate/contracts=lib/solmate/src'
]

[fuzz]
runs = 64

[invariant]
runs = 128
depth = 64
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
